### ISSUE TITLE
Zenity was better than Actions UI

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/cinnamon-spices-actions#279]
### Action version/Build date

1.1.0 (2024-03-16 19:08:51)

### Cinnamon version

6.0.4

### Distribution

Mint 21.3

### Action name and maintainer

move-into-a-new-folder@anaximeno @anaximeno

### What happened?

Hi @anaximeno, thanks for your work providing Cinnamon actions! Unfortunatedly, your new Actions UI, as far as it is now, has some flaws zenity didn't have. For example, you can't press enter in the entry field to trigger a click to the OK button, you always have to use the mouse or click TAB two times before pressing enter. It'd be great if you could add a trigger-default attribute or something like that GTK allows you to use so pressing enter in the entry will trigger the default button of the dialog.
Moreover, the window content needs to be centered and/or at least have some margin. Just look at the screenshot comparing a sample zenity dialog with your current AUI dialog.

### Other information

![screenshot comparing a sample zenity dialog with an actions-ui dialog from anaximeno](https://github.com/linuxmint/cinnamon-spices-actions/assets/118076740/c46e3a80-ceb4-4c1e-af89-6e8f9865bb11)

**Comment by anaximeno** [comment]
Sup @carlosmintfan,

Yeah, I've also noted some of these regressions and plan to fix them in next versions of the Actions UI.

**Comment by carlosmintfan** [comment]
Your UI is cross-actions, right? Then I'd suggest using a submodule so you don't have to update it for every action of you. (Just a suggestion for you :smile: )

**Comment by anaximeno** [comment]
Yes, I intend to use it across some of the actions. I did consider using it as a submodule but decided not to because that would require changes that don't seem to be adequate for the context in this repo it seems to me that each action and all the code and config files relative to it should be contained inside of the directory of the action. Creating a submodule would require adding a .gitsubmodule config inside the root of this repository to manage that, also my major concern would be if the deploy mechanism Mint uses on their servers supports dealing with submodules, otherwise, it could be possible that when downloading the action from the website or even using the official actions manager on the operating system, everything but the UI module would be downloaded. Another point is that I want the users of the UI to be able to choose a specific version and freeze to that version if they want to (that's why I determine what is the current version inside the aui.py file), this would be possible using submodules, but it's easier to manage just importing the file at a specific version (and is also easier to modify if someone just wants to use that specific version as a base for a more context tailored case).
